### ISSUE TITLE
Backend implementation roadmap

### ISSUE THREAD

**Issue by eliemichel** [Evernest/Evernest#23]
Keywords: Agent, Producer, Reader, Writer

 * [x] Test strem system in RAM
 * [x] Mechanism to recover stream from Id
 * [x] Create main blob container
 * [x] Create Stream in Azure
 * [x] Implement Producer
 * [x] Implement Reader
 * [x] Implement  WriteLocker
