### ISSUE TITLE
Website implementation roadmap

### ISSUE THREAD

**Issue by eliemichel** [Evernest/Evernest#24]
Server-side:

 * [x] Base MVC mechanism
 * [x] User registration
 * [x] User authentication

Web interface:

 * [x] General layout (to be documented)
 * [x] Display user information (list of streams and sources)
 * [x] Stream-related page (edit/add/push/pull)
 * [x] Source-related page (edit/add/rights)

Content:

 * [x] Add content to Home/Help/etc
 * [x] Change CSS theme
