### ISSUE TITLE
API implementation roadmap

### ISSUE THREAD

**Issue by eliemichel** [Evernest/Evernest#4]
The full API as it is (actually will be) described in the wiki (a draft is now available in the `doc/` directory) has to be implemented step by step. This issue set what is prioritary.
- [x] Base API mechanism
- [x] Push into and pull from streams (first API actions)
- [x] All endpoints implemented
- [x] Add right `Content-Type` to responses
- [x] Handle `Accept` header from requests (WIP: [x] JSON [ ] XML)
- [ ] Return well typed data
- [ ] Paging
- [ ] Authentication
- [ ] Visibility and rights

Improvement:
- [ ] Selectors
- [ ] Rate limits
- [ ] High-level API
