### ISSUE TITLE
Frontend implementation roadmap

### ISSUE THREAD

**Issue by raphaelrieuhelft** [Evernest/Evernest#5]
Internal :
* [x] Base user rights mechanism
* [x] Base source rights mechanism
* [x] Make all data on users and streams serializable and stored in back-end
* [x] Introduce SystemStream object
* [x] Manage startup/shutdown (loading from master stream to projections)

Improvements :
* [ ] Regularly store projections into a system stream (ProjectionStream)

External :
- [x] Authenticate sources
- [x] User rights management (Is Users class functional ?)
- [x] Source rights management
- [x] Stream creation (requires corresponding backend functionality)
- [x] Push and pull events (requires corresponding backend functionality)
- [x] All requests implemented

**Comment by dianegalloiswong** [comment]
We decided not to store saves of projections in history stream, as it would require to have contracts over the structures used in them. We rather read all system events in history stream to rebuild the projections at startup.
